# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
 baseurl:  # the subpath of your site, e.g. /blog
 url:  https://gurata.github.io/hyperG.github.io/ # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: gurata
user_description: 
user_title: Software Developer
email: korjsh91@naver.com
twitter_username: 
github_username:  gurata
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
